/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_javajindemo_AndroidJNI */

#ifndef _Included_com_example_javajindemo_AndroidJNI
#define _Included_com_example_javajindemo_AndroidJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_javajindemo_AndroidJNI
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_javajindemo_AndroidJNI_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
